The setup and config scripts are pretty decent. The assimilate and pmo scripts are untested.
git-svn-id: https://svn-dares-dart.cgd.ucar.edu/DART/branches/cesm_clm@12120 dfa8782c-da17-4c45-ba5c-5625b50a00d6

Former-commit-id: d3a63a91d86a234140873e64261aa8b017390d84

diff --git a/models/clm/shell_scripts/CESM2_0/CESM2_0_setup_ensemble b/models/clm/shell_scripts/CESM2_0/CESM2_0_setup_ensemble
--- a/models/clm/shell_scripts/CESM2_0/CESM2_0_setup_ensemble
+++ b/models/clm/shell_scripts/CESM2_0/CESM2_0_setup_ensemble
@@ -1,6 +1,6 @@
 #!/bin/csh
 #
-# 
+#
 # provided by UCAR, "as is", without charge, subject to all terms of use at
 # http://www.image.ucar.edu/DAReS/DART/DART_download
 #
@@ -50,7 +50,7 @@ setenv num_instances  4
 #                 the long-term archiver is invoked to move these files to permanent storage.
 #                 Files will remain here until the long-term archiver moves it to permanent storage.
 # dartroot        Location of the root of _your_ DART installation
-# baseobsdir      Part of the directory name containing the obs_seq.out files to be used in the 
+# baseobsdir      Part of the directory name containing the obs_seq.out files to be used in the
 #                 assimilation. The year, month, and filename will be provided in assimilate.csh.
 #                 Will be inherited by CESM#_#_DART_config and inserted into assimilate.csh
 # ==============================================================================
@@ -120,7 +120,7 @@ if ( ${caseroot} == `pwd` ) then
    echo "ERROR: the setup script should not be located in the caseroot"
    echo "directory, because all files in the caseroot dir will be removed"
    echo "before creating the new case.  move the script to a safer place."
-   exit 11
+   exit 1
 endif
 
 echo "removing old files from ${caseroot}"
@@ -136,29 +136,29 @@ ${cesmroot}/cime/scripts/create_newcase  --res  ${resolution} \
                                          --case ${caseroot} \
                                          --project ${project} \
                                          --run-unsupported \
-                                         --ninst ${num_instances} || exit 1
+                                         --ninst ${num_instances} || exit 2
 
 # ==============================================================================
 # Preserve a copy of this script as it was run.
 # Copy the DART setup script (CESM_DART_config) to CASEROOT.
-# Since we know the DARTROOT and BASEOBSDIR now, record them into 
+# Since we know the DARTROOT and BASEOBSDIR now, record them into
 # CASEROOT/CESM_DART_config now.
 # ==============================================================================
 
 set ThisFileName = $0:t
 ${COPY} $ThisFileName ${caseroot}/${ThisFileName}.original
 
-if (   -e ${dartroot}/models/clm/shell_scripts/CESM2_0_DART_config ) then
+if (   -e ${dartroot}/models/clm/shell_scripts/CESM2_0/CESM2_0_DART_config ) then
    sed -e "s#BOGUS_DART_ROOT_STRING#${dartroot}#" \
        -e "s#BOGUS_DART_OBS_STRING#${baseobsdir}#" \
        -e "s#BOGUS_CASEROOT_STRING#${caseroot}#" \
-          ${dartroot}/models/clm/shell_scripts/CESM2_0_DART_config \
-           >! ${caseroot}/CESM_DART_config  || exit 20
+          ${dartroot}/models/clm/shell_scripts/CESM2_0/CESM2_0_DART_config \
+           >! ${caseroot}/CESM_DART_config  || exit 3
    chmod 755  ${caseroot}/CESM_DART_config
 else
    echo "ERROR: the script to configure for data assimilation is not available."
-   echo "       ${dartroot}/models/clm/shell_scripts/CESM2_0_DART_config MUST exist."
-   exit 21
+   echo "       ${dartroot}/models/clm/shell_scripts/CESM2_0/CESM2_0_DART_config MUST exist."
+   exit 4
 endif
 
 # ==============================================================================
@@ -174,7 +174,7 @@ end
 
 # Get a bunch of environment variables.
 # If any of these are changed by xmlchange calls in this program,
-# then they must be explicty changed with setenv calls too.  
+# then they must be explicty changed with setenv calls too.
 #
 setenv TEST_MPI           `./xmlquery MPI_RUN_COMMAND    --value`
 setenv CLM_CONFIG_OPTS    `./xmlquery CLM_CONFIG_OPTS    --value`
@@ -190,9 +190,9 @@ setenv MAX_TASKS_PER_NODE `./xmlquery MAX_TASKS_PER_NODE --value`
 if ( ${COMP_ATM} != datm ) then
    echo " "
    echo "ERROR: This setup script is not appropriate for active atmospheric compsets."
-   echo "ERROR: Please use the models/CESM/shell_scripts examples for that case."
+   echo "ERROR: Please use the models/CESM/shell_scripts/CESM2_0 examples for that case."
    echo " "
-   exit 40
+   exit 5
 endif
 
 #> @TODO stream template files & multiple years. Do we need to specify
@@ -259,7 +259,7 @@ setenv startdate 1998-01-01
 #set start_day =  "01"
 ./xmlchange RUN_STARTDATE=${startdate}
 
-# Data assimilation is turned off initially. After things are working, you can 
+# Data assimilation is turned off initially. After things are working, you can
 # turn it on by running CASEROOT/CESM_DART_config
 
 @ nodes_per_instance = 1
@@ -287,14 +287,14 @@ setenv startdate 1998-01-01
 ./xmlchange ROOTPE_ESP=0,NTHRDS_ESP=$nthreads,NTASKS_ESP=$esp_tasks,NINST_ESP=1
 
 # Before CESM1_5 we ran in DART mode without assimilating by editing case.run to choose
-# no_assimilate.csh or assimilate.csh.  Now the script to be run is determined by 
+# no_assimilate.csh or assimilate.csh.  Now the script to be run is determined by
 # CESM's env_run.xml DATA_ASSIMILATION* variables.
 # Having DATA_ASSIMILATION = true. and specifying what script you want to run
 # is always correct.
 #
 # DATA_ASSIMILATION_CYCLES says how many cycles to run in each job before a RESUBMIT.
 # Set to 1 for the first cycle.
-# When the job (not each cycle) is finished the short_term archiver will run and, 
+# When the job (not each cycle) is finished the short_term archiver will run and,
 # if RESUBMIT > 0, (re)submit a new case.run job.
 
 ./xmlchange DATA_ASSIMILATION=TRUE
@@ -304,7 +304,7 @@ setenv startdate 1998-01-01
 ./xmlchange DATA_ASSIMILATION_SCRIPT=${CASEROOT}/no_assimilate.csh
 
 
-./case.setup || exit 9
+./case.setup || exit 6
 echo "case setup finished"
 
 # ====================================
@@ -325,8 +325,8 @@ endif
 
 # DEBUG = TRUE implies turning on run and compile time debugging.
 # INFO_DBUG level of debug output, 0=minimum, 1=normal, 2=more, 3=too much.
-./xmlchange DEBUG=FALSE
-./xmlchange INFO_DBUG=0
+./xmlchange DEBUG=TRUE
+./xmlchange INFO_DBUG=1
 
 @ inst = 1
 while ( $inst <= $num_instances )
@@ -338,11 +338,16 @@ while ( $inst <= $num_instances )
     # ===========================================================================
     # DATM namelist
 
-    echo "streams  = 'datm.streams.txt.CPLHISTForcing.Solar_$inst_string        $stream_year_align $stream_year_first $stream_year_last'," >> ${fname}
-    echo "           'datm.streams.txt.CPLHISTForcing.nonSolarFlux_$inst_string $stream_year_align $stream_year_first $stream_year_last'," >> ${fname}
-    echo "           'datm.streams.txt.CPLHISTForcing.State1hr_$inst_string     $stream_year_align $stream_year_first $stream_year_last'"  >> ${fname}
-    echo "           'datm.streams.txt.CPLHISTForcing.State3hr_$inst_string     $stream_year_align $stream_year_first $stream_year_last'"  >> ${fname}
-    echo "           'datm.streams.txt.presaero.clim_2000_$inst_string 1 1 1'"  >> ${fname}
+    set FILE1 = datm.streams.txt.CPLHISTForcing.Solar_$inst_string
+    set FILE2 = datm.streams.txt.CPLHISTForcing.nonSolarFlux_$inst_string
+    set FILE3 = datm.streams.txt.CPLHISTForcing.State1hr_$inst_string
+    set FILE4 = datm.streams.txt.CPLHISTForcing.State3hr_$inst_string
+
+    echo "streams = '$FILE1 $stream_year_align $stream_year_first $stream_year_last'," >> ${fname}
+    echo "          '$FILE2 $stream_year_align $stream_year_first $stream_year_last'," >> ${fname}
+    echo "          '$FILE3 $stream_year_align $stream_year_first $stream_year_last'," >> ${fname}
+    echo "          '$FILE4 $stream_year_align $stream_year_first $stream_year_last'," >> ${fname}
+    echo "          'datm.streams.txt.presaero.clim_2000_$inst_string 1 1 1'"          >> ${fname}
     echo "vectors  = 'u:v' "     >> ${fname}
     echo "mapmask  = 'nomask', " >> ${fname}
     echo "           'nomask', " >> ${fname}
@@ -354,14 +359,11 @@ while ( $inst <= $num_instances )
     echo "           'linear'  " >> ${fname}
 
     # Create stream files for each ensemble member
-    ${COPY} ${dartroot}/models/clm/shell_scripts/datm.streams.txt.CPLHISTForcing.Solar_complete \
-                                             user_datm.streams.txt.CPLHISTForcing.Solar_${inst_string}
-    ${COPY} ${dartroot}/models/clm/shell_scripts/datm.streams.txt.CPLHISTForcing.nonSolarFlux_complete \
-                                             user_datm.streams.txt.CPLHISTForcing.nonSolarFlux_${inst_string}
-    ${COPY} ${dartroot}/models/clm/shell_scripts/datm.streams.txt.CPLHISTForcing.State1hr_complete \
-                                             user_datm.streams.txt.CPLHISTForcing.State1hr_${inst_string}
-    ${COPY} ${dartroot}/models/clm/shell_scripts/datm.streams.txt.CPLHISTForcing.State3hr_complete \
-                                             user_datm.streams.txt.CPLHISTForcing.State3hr_${inst_string}
+    set SOURCEDIR = ${dartroot}/models/clm/shell_scripts/CESM2_0
+    ${COPY} ${SOURCEDIR}/datm.streams.txt.CPLHISTForcing.Solar_complete        user_${FILE1}
+    ${COPY} ${SOURCEDIR}/datm.streams.txt.CPLHISTForcing.nonSolarFlux_complete user_${FILE2}
+    ${COPY} ${SOURCEDIR}/datm.streams.txt.CPLHISTForcing.State1hr_complete     user_${FILE3}
+    ${COPY} ${SOURCEDIR}/datm.streams.txt.CPLHISTForcing.State3hr_complete     user_${FILE4}
 
     foreach FNAME ( user_datm.streams.txt*_${inst_string} )
        echo "modifying $FNAME"
@@ -369,7 +371,7 @@ while ( $inst <= $num_instances )
        sed s/RUNYEAR/${stream_year_first}/g temp >! $FNAME
     end
     ${REMOVE} temp
-    
+
    # ===========================================================================
    set fname = "user_nl_clm"_${inst_string}
    # ===========================================================================
@@ -390,16 +392,15 @@ end
 
 ./preview_namelists
 
-
 #===============================================================================
-# Copy modified CICE codes into SourceMods
+# Copy modified CLM codes into SourceMods
 # ==============================================================================
 
 #${COPY} $dartroot/models/cice/SourceMods/ice_restart_driver.F90 $caseroot/SourceMods/src.cice/
 #${COPY} /glade/p/work/yfzhang/cesmcases/cesm2_0_beta05/seq_rest_mod.F90 $caseroot/SourceMods/src.drv/
 #${COPY} /glade/scratch/yfzhang/inputdata_cam/ice/cice/$startdate/* $rundir/
 
-# ./case.build || exit 10
+# ./case.build || exit 7
 
 # ==============================================================================
 # What to do next
@@ -429,12 +430,12 @@ Time to check the case.
    cd ${caseroot}
    ./CESM_DART_config
 
-6) Make sure the DART-related parts are appropriate. 
+6) Make sure the DART-related parts are appropriate.
    Check the input.nml
    Check the assimilate.csh
    ./case.submit
 
-7) If that works 
+7) If that works
    ./xmlchange CONTINUE_RUN=TRUE
    that sort of thing
 -------------------------------------------------------------------------
