Testing restarting from ensemble members in /glade/p/image/RDA_strawman/CESM_ensembles/CLM/CLM5BGC-Crop/1999-01-01-00000 and it advanced correctly.  This does not run pmo at this point.
git-svn-id: https://svn-dares-dart.cgd.ucar.edu/DART/branches/cesm_clm@12453 dfa8782c-da17-4c45-ba5c-5625b50a00d6

Former-commit-id: 41ed8928c2e38cd99a34ac8b6f9111794a31d66d

diff --git a/models/clm/shell_scripts/cesm2_0/CLM5_pmo b/models/clm/shell_scripts/cesm2_0/CLM5_pmo
--- a/models/clm/shell_scripts/cesm2_0/CLM5_pmo
+++ b/models/clm/shell_scripts/cesm2_0/CLM5_pmo
@@ -166,14 +166,14 @@ switch ("`hostname`")
          # NCAR "yellowstone"
          set   MOVE = '/bin/mv -v'
          set   COPY = '/bin/cp -v --preserve=timestamps'
-         set   LINK = '/bin/ln -vsf'
+         set   LINK = '/bin/ln -vs'
          set REMOVE = '/bin/rm -rf'
       breaksw
    default:
          # NERSC "hopper", TACC "stampede" ... many more
          set   MOVE = 'mv -v'
          set   COPY = 'cp -v --preserve=timestamps'
-         set   LINK = 'ln -vsf'
+         set   LINK = 'ln -vs'
          set REMOVE = 'rm -rf'
       breaksw
 endsw
@@ -236,8 +236,8 @@ cd ${caseroot}
 
 # Save a copy for debug purposes
 foreach FILE ( *xml )
-   if ( ! -e        ${FILE}.original ) then
-      ${COPY} $FILE ${FILE}.original
+   if ( ! -e          ${FILE}.original ) then
+      ${COPY} ${FILE} ${FILE}.original
    endif
 end
 
@@ -270,6 +270,9 @@ endif
 setenv resubmit            0
 setenv stop_option         nhours
 setenv stop_n              24
+
+@ clm_dtime = 1800
+@ h1nsteps = $stop_n * 3600 / $clm_dtime
 
 # stream_year_first  settings for the stream files for the Data Atmosphere (DATM).
 # stream_year_last
@@ -318,14 +321,13 @@ set stream_year_last  = 2010
 
 ./xmlchange START_TOD=$start_tod
 ./xmlchange RUN_REFTOD=$reftod
-./xmlchange GET_REFCASE=TRUE
+./xmlchange GET_REFCASE=FALSE
 
 # pnetcdf is default
 ./xmlchange PIO_TYPENAME=netcdf
 
-set TEST_MPI = `./xmlquery --value MPI_RUN_COMMAND'`
 if (${TEST_MPI} == 'UNSET') then
-   ./xmlchange MPI_RUN_COMMAND=mpiexec.mpt
+   ./xmlchange MPI_RUN_COMMAND=mpiexec_mpt
 endif
 
 # Task layout:
@@ -334,6 +336,7 @@ endif
 # a whole number of nodes which is the recommended configuration.
 # This is a decent layout for a single instance, but should be explored.
 # Presently, all components run 'serially' - one after another.
+# CIME interprets a negative task count as representing the number of nodes.
 
 @ nthreads = 1
 @ nodes_per_instance = 4
@@ -455,6 +458,157 @@ while ( $inst <= $num_instances )
 
    @ inst ++
 end
+
+./preview_namelists || exit 3
+
+# ==============================================================================
+# Stage the restarts now that the run directory exists
+# ==============================================================================
+
+echo "staging restarts"
+
+set init_time = ${reftimestamp}
+
+cat << EndOfText >! stage_cesm_files
+#!/bin/csh -f
+# This script can be used to help restart an experiment from any previous step.
+# The appropriate files are copied to the RUN directory.
+#
+# Before running this script:
+#  1) be sure CONTINUE_RUN is set correctly in the env_run.xml file in
+#     your CASEROOT directory.
+#     CONTINUE_RUN=FALSE => you are starting over at the initial time.
+#     CONTINUE_RUN=TRUE  => you are starting from a previous step but not
+#                           the very first one.
+#  2) be sure 'restart_time' is set to the day and time that you want to
+#     restart from if not the initial time.
+
+set restart_time = $init_time
+
+# get the settings for this case from the CESM environment
+cd ${caseroot}
+
+setenv CONTINUE_RUN   `./xmlquery CONTINUE_RUN     --value`
+setenv RUNDIR         `./xmlquery RUNDIR           --value`
+setenv DOUT_S         `./xmlquery DOUT_S           --value`
+setenv DOUT_S_ROOT    `./xmlquery DOUT_S_ROOT      --value`
+setenv CASE           `./xmlquery CASE             --value`
+
+cd \${RUNDIR}
+
+echo 'Copying the required CESM files to the run directory to rerun'
+echo 'a previous step.  CONTINUE_RUN from env_run.xml is' \${CONTINUE_RUN}
+if ( \${CONTINUE_RUN} == TRUE ) then
+  echo 'so files for some later step than the initial one will be restaged.'
+  echo "Date to reset files to is: \${restart_time}"
+else
+  echo 'so files for the initial step of this experiment will be restaged.'
+  echo "Date to reset files to is: ${init_time}"
+endif
+echo ''
+
+if ( \${CONTINUE_RUN} == TRUE ) then
+
+   #----------------------------------------------------------------------
+   # This block copies over a set of restart files from any previous step of
+   # the experiment that is NOT the initial step.
+   # After running this script resubmit the job to rerun.
+   #----------------------------------------------------------------------
+
+   echo "Staging restart files for run date/time: " \${restart_time}
+
+   #  The short term archiver is on, so the files we want should be in one
+   #  of the short term archive 'rest' restart directories.  This assumes
+   #  the long term archiver has NOT copied these files to the HPSS yet.
+
+   if (  \${DOUT_S} == TRUE ) then
+
+      # The restarts should be in the short term archive directory.
+
+      set RESTARTDIR = \${DOUT_S_ROOT}/rest/\${restart_time}
+
+      if ( ! -d \${RESTARTDIR} ) then
+
+         echo "restart file directory not found: "
+         echo " \${RESTARTDIR}"
+         echo "If the long-term archiver is on, you may have to restore this directory first."
+         echo "You can also check for either a .sta or a .sta2 hidden subdirectory in"
+         echo "\${DOUT_S_ROOT}"
+         echo "which may contain the 'rest' directory you need,"
+         echo "and then modify RESTARTDIR in this script."
+         exit -1
+
+      endif
+
+      ${COPY} \${RESTARTDIR}/* . || exit -1
+
+   else
+
+      # The short term archiver is off, which leaves all the restart files
+      # in the run directory.  The rpointer files must still be updated to
+      # point to the files with the right day/time.
+
+      @ inst=1
+      while (\$inst <= 1)
+
+         set inst_string = ''
+
+         echo "\${CASE}.cpl\${inst_string}.r.\${restart_time}.nc"    >! rpointer.drv\${inst_string}
+         echo "\${CASE}.clm2\${inst_string}.r.\${restart_time}.nc"   >! rpointer.lnd\${inst_string}
+         echo "\${CASE}.datm\${inst_string}.r.\${restart_time}.nc"   >! rpointer.atm\${inst_string}
+         echo "\${CASE}.datm\${inst_string}.rs1.\${restart_time}.nc" >> rpointer.atm\${inst_string}
+         echo "\${CASE}.mosart\${inst_string}.r.\${restart_time}.nc" >! rpointer.rof\${inst_string}
+
+         @ inst ++
+      end
+
+      # If the multi-driver is not being used,
+      # there is only a single coupler restart file.
+      echo "\${case}.cpl.r.\${restart_time}.nc" >! rpointer.drv
+
+   endif
+
+   echo "All files reset to rerun experiment step for time " \$restart_time
+
+else     # CONTINUE_RUN == FALSE
+
+   #----------------------------------------------------------------------
+   # This block links the right files to rerun the initial (very first)
+   # step of an experiment.  The names and locations are set during the
+   # building of the case; to change them rebuild the case.
+   # After running this script resubmit the job to rerun.
+   #----------------------------------------------------------------------
+
+   @ inst=1
+   while (\$inst <= 1)
+
+      set inst_string = ''
+
+      if ( $SingleInstanceRefcase ) then
+         set true_string = ''
+         echo "Staging initial files."
+      else
+         set true_string = `printf _%04d $TRUTHinstance`
+         echo "Staging initial files from instance $TRUTHinstance for the truth run."
+      endif
+
+      ${LINK} ${stagedir}/${refcase}.clm2\${true_string}.r.${init_time}.nc \
+                          ${refcase}.clm2\${inst_string}.r.${init_time}.nc || exit 2
+
+      ${LINK} ${stagedir}/${refcase}.mosart\${true_string}.r.${init_time}.nc \
+                          ${refcase}.mosart\${inst_string}.r.${init_time}.nc || exit 3
+      @ inst ++
+   end
+
+   echo "All files set to run the FIRST experiment step at time" $init_time
+
+endif
+exit 0
+
+EndOfText
+chmod 0755 stage_cesm_files
+
+./stage_cesm_files || exit 2
 
 ./case.build || exit 7
 
