Uses the right set of stream template files if only using 1 year.
git-svn-id: https://svn-dares-dart.cgd.ucar.edu/DART/branches/cesm_clm@12914 dfa8782c-da17-4c45-ba5c-5625b50a00d6

Former-commit-id: 390c5be52f83f27e0665fae658de83ac34e8de9f

diff --git a/models/clm/shell_scripts/cesm2_0/CLM5_setup_pmo b/models/clm/shell_scripts/cesm2_0/CLM5_setup_pmo
--- a/models/clm/shell_scripts/cesm2_0/CLM5_setup_pmo
+++ b/models/clm/shell_scripts/cesm2_0/CLM5_setup_pmo
@@ -5,19 +5,14 @@
 # http://www.image.ucar.edu/DAReS/DART/DART_download
 #
 # DART $Id$
+#
+# ------------------------------------------------------------------------------
+# Purpose: takes a single instance from a spun-up ensemble and advances CLM in
+#          24-hour segments. If that works, the setup can be modified to run
+#          perfect_model_obs to harvest synthetic observations from the single
+#          instance, which is now the true state of the system.
 
-#-----------------------------------------------------------------------
-# Purpose, describe things here, etc.
-#-----------------------------------------------------------------------
-#
-# CLM5_setup_pmo    takes a single instance from a spun-up ensemble and
-#                   advances CLM in 24hour segments. If that works,
-#                   the setup can be modified to run perfect_model_obs to
-#                   harvest synthetic observations from the single instance,
-#                   which is now the true state of the system.
-#
-# ==============================================================================
-# The DART_params.csh contains many (if not all) of the run-time settings 
+# The DART_params.csh contains many (if not all) of the run-time settings
 
 source DART_params.csh
 
@@ -39,6 +34,10 @@ setenv st_archive_time 02:00:00
 
 # ==============================================================================
 # Create the case - this creates the CASEROOT directory.
+#
+# For list of the pre-defined component sets: ./create_newcase -list
+# To create a variant compset, see the CESM documentation and carefully
+# incorporate any needed changes into this script.
 # ==============================================================================
 
 # FATAL idea to make caseroot the same dir as where this setup script is
@@ -117,13 +116,13 @@ endif
 ./xmlchange RUNDIR=${rundir}
 
 # This comes from http://esmci.github.io/cime/data_models/data-atm.html
-# "Note If DATM_MODE is set to CPLHIST, it is normally assumed that the model 
-# domain will be identical to all of the stream domains. To ensure this, the 
-# xml variables ATM_DOMAIN_PATH and ATM_DOMAIN_FILE are ignored and a valid 
-# setting must be given for DATM_CPLHIST_DOMAIN_FILE. If DATM_CPLHIST_DOMAIN_FILE 
-# is set to null, then the datm component domain information is read in from 
-# the first coupler history file in the target stream and it is assumed that the 
-# first coupler stream file that is pointed to contains the domain information 
+# "Note If DATM_MODE is set to CPLHIST, it is normally assumed that the model
+# domain will be identical to all of the stream domains. To ensure this, the
+# xml variables ATM_DOMAIN_PATH and ATM_DOMAIN_FILE are ignored and a valid
+# setting must be given for DATM_CPLHIST_DOMAIN_FILE. If DATM_CPLHIST_DOMAIN_FILE
+# is set to null, then the datm component domain information is read in from
+# the first coupler history file in the target stream and it is assumed that the
+# first coupler stream file that is pointed to contains the domain information
 # for that stream. This is the default that should be used for this mode."
 
 ./xmlchange DATM_MODE=CPLHIST
@@ -217,6 +216,22 @@ endif
 ./xmlchange INFO_DBUG=0
 
 # ==============================================================================
+# If the experiment only spans one year, copy a stream template for a single year
+# otherwise, use 'all' the years.
+
+if (${stream_year_first} == ${stream_year_last}) then
+   set STREAMFILE_SOLAR        = datm.streams.txt.CPLHISTForcing.Solar_single_year
+   set STREAMFILE_NONSOLARFLUX = datm.streams.txt.CPLHISTForcing.nonSolarFlux_single_year
+   set STREAMFILE_STATE1HR     = datm.streams.txt.CPLHISTForcing.State1hr_single_year
+   set STREAMFILE_STATE3HR     = datm.streams.txt.CPLHISTForcing.State3hr_single_year
+else
+   set STREAMFILE_SOLAR        = datm.streams.txt.CPLHISTForcing.Solar_complete
+   set STREAMFILE_NONSOLARFLUX = datm.streams.txt.CPLHISTForcing.nonSolarFlux_complete
+   set STREAMFILE_STATE1HR     = datm.streams.txt.CPLHISTForcing.State1hr_complete
+   set STREAMFILE_STATE3HR     = datm.streams.txt.CPLHISTForcing.State3hr_complete
+endif
+
+# ==============================================================================
 # Modify namelist templates for each instance.
 #
 # In a hybrid run with CONTINUE_RUN = FALSE (i.e. just starting up):
@@ -261,10 +276,10 @@ while ( $inst <= $num_instances )
 
    # Create stream files for each ensemble member
    set SOURCEDIR = ${dartroot}/models/clm/shell_scripts/cesm2_0
-   ${COPY} ${SOURCEDIR}/datm.streams.txt.CPLHISTForcing.Solar_complete        user_${FILE1} || exit 1
-   ${COPY} ${SOURCEDIR}/datm.streams.txt.CPLHISTForcing.nonSolarFlux_complete user_${FILE2} || exit 1
-   ${COPY} ${SOURCEDIR}/datm.streams.txt.CPLHISTForcing.State1hr_complete     user_${FILE3} || exit 1
-   ${COPY} ${SOURCEDIR}/datm.streams.txt.CPLHISTForcing.State3hr_complete     user_${FILE4} || exit 1
+   ${COPY} ${SOURCEDIR}/${STREAMFILE_SOLAR}        user_${FILE1} || exit 1
+   ${COPY} ${SOURCEDIR}/${STREAMFILE_NONSOLARFLUX} user_${FILE2} || exit 1
+   ${COPY} ${SOURCEDIR}/${STREAMFILE_STATE1HR}     user_${FILE3} || exit 1
+   ${COPY} ${SOURCEDIR}/${STREAMFILE_STATE3HR}     user_${FILE4} || exit 1
 
    foreach FNAME ( user_datm.streams.txt*${inst_string} )
       echo "modifying $FNAME"
@@ -276,6 +291,12 @@ while ( $inst <= $num_instances )
    # ===========================================================================
    set fname = "user_nl_clm${inst_string}"
    # ===========================================================================
+
+   # hist_nhtfrq: Per tape series history write frequency.
+   #              positive means in time steps 0=monthly negative means hours
+   #              i.e. 5 means every 24 time-steps and -24 means every day
+   #              Default: 0,-24,-24,-24,-24,-24
+   # hist_mfilt:  Per tape series maximum number of time samples.
 
    echo "hist_empty_htapes = .false."                                     >> ${fname}
    echo "hist_fincl1 = 'FSIF'"                                            >> ${fname}
@@ -465,37 +486,40 @@ chmod 0755 stage_cesm_files
 #         `-- lnd_import_export.F90
 # ==============================================================================
 
-if ( ${use_sourcemods} == TRUE ) then
+if ( ${use_SourceMods} == TRUE ) then
 
    if (    -d    ~/${cesmtag}/SourceMods ) then
-      ${COPY} -r ~/${cesmtag}/SourceMods/* ${caseroot}/SourceMods/
-   
+      ${COPY} -r ~/${cesmtag}/SourceMods/* ${caseroot}/SourceMods/ || exit 3
+
       set clm_opts = `echo $CLM_CONFIG_OPTS | sed -e "s/-//"`
-   
+
       @ iarg = 1
       while ($iarg <= $#clm_opts)
-   
+
          @ iargp1 = $iarg + 1
          set option = $clm_opts[$iarg]
          set  value = $clm_opts[$iargp1]
-   
+
          switch ( ${option} )
+
+            # TODO ... this LINK did not fail when the directory structure
+            # was unexpected ... make a better check ...
 
             case "phys":
                if ( -e    SourceMods/src.clm/${value} ) then
                   cd      SourceMods/src.clm
-                  ${LINK} ${value}/*/*F90 .
+                  ${LINK} ${value}/*/*F90 . || exit 3
                   cd      ../..
                else
                   echo "No SourceMods for CLM <${value}>."
                   echo "Got the version from CLM_CONFIG_OPTS ...  <${CLM_CONFIG_OPTS}>"
                endif
             breaksw
-   
+
             default:
             breaksw
          endsw
-   
+
          @ iarg = $iarg + 2
       end
    else
