All routines now use the DART_params.csh Also added flags so ./case.submit sends mail
git-svn-id: https://svn-dares-dart.cgd.ucar.edu/DART/branches/cesm_clm@12929 dfa8782c-da17-4c45-ba5c-5625b50a00d6

Former-commit-id: 1c1bb79a587c5b893edda90c7be34563ac01c72a

diff --git a/models/clm/shell_scripts/cesm2_0/CLM5_setup_assimilation b/models/clm/shell_scripts/cesm2_0/CLM5_setup_assimilation
--- a/models/clm/shell_scripts/cesm2_0/CLM5_setup_assimilation
+++ b/models/clm/shell_scripts/cesm2_0/CLM5_setup_assimilation
@@ -41,10 +41,6 @@ setenv st_archive_time 06:00:00
 # ==============================================================================
 # Create the case - this creates the CASEROOT directory.
 #
-# For list of the pre-defined component sets: ./create_newcase -list
-# To create a variant compset, see the CESM documentation and carefully
-# incorporate any needed changes into this script.
-
 # FATAL idea to make caseroot the same dir as where this setup script is
 # since the build process removes all files in the caseroot dir before
 # populating it.  try to prevent shooting yourself in the foot.
@@ -108,7 +104,7 @@ setenv CASEROOT              `./xmlquery CASEROOT              --value`
 
 if ( (${COMP_OCN} != socn) || (${COMP_ATM} != datm) ) then
    echo " "
-   echo "ERROR: This setup script is not appropriate for active ocean or atmospheric compsets."
+   echo "ERROR: This script is not appropriate for active ocean or atmospheric compsets."
    echo " "
    exit 5
 endif
@@ -206,12 +202,13 @@ echo "setting up the case ... "
 echo "case setup finished."
 
 # ==============================================================================
+# These are archiving options that may be used.
 
 if (${short_term_archiver} == 'off') then
    ./xmlchange DOUT_S=FALSE
 else
    ./xmlchange DOUT_S=TRUE
-   ./xmlchange --subgroup case.st_archive --id JOB_QUEUE         --val ${st_archive_queue}
+   ./xmlchange --subgroup case.st_archive --id JOB_QUEUE          --val ${st_archive_queue}
    ./xmlchange --subgroup case.st_archive --id JOB_WALLCLOCK_TIME --val ${st_archive_time}
 endif
 
@@ -227,14 +224,14 @@ endif
 
 if (${stream_year_first} == ${stream_year_last}) then
    set STREAMFILE_SOLAR        = datm.streams.txt.CPLHISTForcing.Solar_single_year
-   set STREAMFILE_NONSOLARFLUX = datm.streams.txt.CPLHISTForcing.nonSolarFlux_single_year
    set STREAMFILE_STATE1HR     = datm.streams.txt.CPLHISTForcing.State1hr_single_year
    set STREAMFILE_STATE3HR     = datm.streams.txt.CPLHISTForcing.State3hr_single_year
+   set STREAMFILE_NONSOLARFLUX = datm.streams.txt.CPLHISTForcing.nonSolarFlux_single_year
 else
    set STREAMFILE_SOLAR        = datm.streams.txt.CPLHISTForcing.Solar_complete
-   set STREAMFILE_NONSOLARFLUX = datm.streams.txt.CPLHISTForcing.nonSolarFlux_complete
    set STREAMFILE_STATE1HR     = datm.streams.txt.CPLHISTForcing.State1hr_complete
    set STREAMFILE_STATE3HR     = datm.streams.txt.CPLHISTForcing.State3hr_complete
+   set STREAMFILE_NONSOLARFLUX = datm.streams.txt.CPLHISTForcing.nonSolarFlux_complete
 endif
 
 # ==============================================================================
@@ -256,9 +253,9 @@ while ( $inst <= $num_instances )
    # DATM namelist
 
    set FILE1 = datm.streams.txt.CPLHISTForcing.Solar${inst_string}
-   set FILE2 = datm.streams.txt.CPLHISTForcing.nonSolarFlux${inst_string}
-   set FILE3 = datm.streams.txt.CPLHISTForcing.State1hr${inst_string}
-   set FILE4 = datm.streams.txt.CPLHISTForcing.State3hr${inst_string}
+   set FILE2 = datm.streams.txt.CPLHISTForcing.State1hr${inst_string}
+   set FILE3 = datm.streams.txt.CPLHISTForcing.State3hr${inst_string}
+   set FILE4 = datm.streams.txt.CPLHISTForcing.nonSolarFlux${inst_string}
    set DOMAINFILE = '/glade/p/cesmdata/cseg/inputdata/share/domains/domain.lnd.fv0.9x1.25_gx1v7.151020.nc'
 
    echo "domainfile = '${DOMAINFILE}'" >> ${fname}
@@ -273,16 +270,16 @@ while ( $inst <= $num_instances )
    echo "           'nomask', " >> ${fname}
    echo "           'nomask'  " >> ${fname}
    echo "tintalgo = 'coszen', " >> ${fname}
-   echo "           'nearest'," >> ${fname}
    echo "           'linear', " >> ${fname}
-   echo "           'linear'  " >> ${fname}
+   echo "           'linear', " >> ${fname}
+   echo "           'nearest' " >> ${fname}
 
    # Create stream files for each ensemble member
    set SOURCEDIR = ${dartroot}/models/clm/shell_scripts/cesm2_0
-   ${COPY} ${SOURCEDIR}/${STREAMFILE_SOLAR}        user_${FILE1} || exit 1
-   ${COPY} ${SOURCEDIR}/${STREAMFILE_NONSOLARFLUX} user_${FILE2} || exit 1
-   ${COPY} ${SOURCEDIR}/${STREAMFILE_STATE1HR}     user_${FILE3} || exit 1
-   ${COPY} ${SOURCEDIR}/${STREAMFILE_STATE3HR}     user_${FILE4} || exit 1
+   ${COPY} ${SOURCEDIR}/${STREAMFILE_SOLAR}         user_${FILE1} || exit 1
+   ${COPY} ${SOURCEDIR}/${STREAMFILE_STATE1HR}      user_${FILE2} || exit 1
+   ${COPY} ${SOURCEDIR}/${STREAMFILE_STATE3HR}      user_${FILE3} || exit 1
+   ${COPY} ${SOURCEDIR}/${STREAMFILE_NONSOLARFLUX}  user_${FILE4} || exit 1
 
    foreach FNAME ( user_datm.streams.txt*${inst_string} )
       echo "modifying $FNAME"
@@ -463,7 +460,7 @@ chmod 0755 stage_cesm_files
 
 #===============================================================================
 # This example has SourceMods that enable CLM to output solar induced fluorescence
-# as a diagnostic variable in the history files as "FSIF".
+# as an additional diagnostic variable ("FSIF") in the history file.
 
 if ( ${use_SourceMods} == TRUE ) then
 
@@ -499,8 +496,9 @@ if ( ${use_SourceMods} == TRUE ) then
          @ iarg = $iarg + 2
       end
    else
-      echo "MESSAGE - No SourceMods for this case."
-      echo "MESSAGE - No SourceMods for this case."
+      echo "ERROR - DART_params.csh use_SourceMods = ${use_SourceMods}"
+      echo "ERROR - but there are no SourceMods in ${SourceModDir}"
+      exit 3
    endif
 endif
 
@@ -523,8 +521,8 @@ Time to check the case.
 
 3) check things
 
-4) run a single day, verify that it works without assimilation
-   ./case.submit
+4) run a single job (and send mail), verify that it works without assimilation
+   ./case.submit -M all
 
 5) IF NEEDED, compile all the DART executables by
    cd  ${dartroot}/models/clm/work
@@ -538,10 +536,11 @@ Time to check the case.
 7) Make sure the DART-related parts are appropriate.
    Check the input.nml
    Check the assimilate.csh or perfect_model.csh - as appropriate
-   ./case.submit
+   ./case.submit -M all
 
 8) If that works
    ./xmlchange CONTINUE_RUN=TRUE
+   ./xmlchange RESUBMIT=11
    that sort of thing
 -------------------------------------------------------------------------
 
diff --git a/models/clm/shell_scripts/cesm2_0/CLM5_startup_freerun b/models/clm/shell_scripts/cesm2_0/CLM5_startup_freerun
--- a/models/clm/shell_scripts/cesm2_0/CLM5_startup_freerun
+++ b/models/clm/shell_scripts/cesm2_0/CLM5_startup_freerun
@@ -11,16 +11,16 @@
 #          Writes out restart files once per month.
 #          All ensembles start from the same (default) input file.
 #
-# Put another way: This script takes the spun-up CLM state supplied with 
+# Put another way: This script takes the spun-up CLM state supplied with
 # the compset and forecasts an ensemble of these. Each ensemble member uses
 # a unique data atmosphere stream file. After some time, the ensemble of
 # CLM states have enough diversity to be a useful initial ensemble for
-# an assimilation experiment. 
+# an assimilation experiment.
 # ------------------------------------------------------------------------------
 
 # Many user-specified variables and settings are read from a DART
 # parameter file "DART_params.csh". This should be configured first.
-# There are still some variables that are logically defined in this script, 
+# There are still some variables that are logically defined in this script,
 # as well as some specifics about the CLM namelists.
 
 source DART_params.csh
@@ -30,10 +30,12 @@ source DART_params.csh
 #
 # run_queue, run_time, st_archive_queue, st_archive_time may be changed at any time
 #
-# TJH: Advancing 80 instances for 1 month using 2 nodes per instance averaged
+# TJH: for a CLM50%BGC-CROP at f09_f09_mg17 resolution,
+#      Advancing 80 instances for 1 month using 2 nodes per instance averaged
 #      about 2000 core hours on cheyenne using 36 tasks and 1 thread per node.
 #      About 625 seconds of wall-clock per month. 2000*60*60/(80*4*36) = 625
 #      Consequently, a year takes a litte more than 2 hours of run_time.
+#      12 months of an 80-member ensemble is about 2.6 Tb of data.
 
 # A 'startup' run_type uses the spun-up CLM state supplied with the compset.
 # stop_option=nmonths,stop_n=12 ... stop after 1 year
@@ -53,7 +55,7 @@ setenv run_queue regular
 setenv run_time 03:00:00
 
 # the short-term archiver is turned off (initially?) to let you explore the
-# run directory 
+# run directory
 
 setenv short_term_archiver off
 setenv st_archive_queue share
@@ -62,10 +64,6 @@ setenv st_archive_time 06:00:00
 # ==============================================================================
 # Create the case - this creates the CASEROOT directory.
 #
-# For list of the pre-defined component sets: ./create_newcase -list
-# To create a variant compset, see the CESM documentation and carefully
-# incorporate any needed changes into this script.
-
 # FATAL idea to make caseroot the same dir as where this setup script is
 # since the build process removes all files in the caseroot dir before
 # populating it.  try to prevent shooting yourself in the foot.
@@ -172,8 +170,7 @@ endif
 # CIME interprets a negative task count as representing the number of nodes.
 # On Cheyenne (at least) using multiple threads is not recommended.
 
-@ nodes_per_instance = 2
-@ nthreads = 1
+@ nthreads = ${number_of_threads}
 
 @ atm_tasks = -1 * ${nodes_per_instance}
 @ cpl_tasks = -1 * ${nodes_per_instance}
@@ -206,8 +203,6 @@ echo "case setup finished."
 
 # ==============================================================================
 # These are archiving options that may be used.
-# You can turn the short/long term archivers on or off ({short,long}_term_archiver),
-# but these settings should be made in either event.
 
 if (${short_term_archiver} == 'off') then
    ./xmlchange DOUT_S=FALSE
@@ -229,14 +224,14 @@ endif
 
 if (${stream_year_first} == ${stream_year_last}) then
    set STREAMFILE_SOLAR        = datm.streams.txt.CPLHISTForcing.Solar_single_year
-   set STREAMFILE_NONSOLARFLUX = datm.streams.txt.CPLHISTForcing.nonSolarFlux_single_year
    set STREAMFILE_STATE1HR     = datm.streams.txt.CPLHISTForcing.State1hr_single_year
    set STREAMFILE_STATE3HR     = datm.streams.txt.CPLHISTForcing.State3hr_single_year
+   set STREAMFILE_NONSOLARFLUX = datm.streams.txt.CPLHISTForcing.nonSolarFlux_single_year
 else
    set STREAMFILE_SOLAR        = datm.streams.txt.CPLHISTForcing.Solar_complete
-   set STREAMFILE_NONSOLARFLUX = datm.streams.txt.CPLHISTForcing.nonSolarFlux_complete
    set STREAMFILE_STATE1HR     = datm.streams.txt.CPLHISTForcing.State1hr_complete
    set STREAMFILE_STATE3HR     = datm.streams.txt.CPLHISTForcing.State3hr_complete
+   set STREAMFILE_NONSOLARFLUX = datm.streams.txt.CPLHISTForcing.nonSolarFlux_complete
 endif
 
 # ==============================================================================
@@ -253,9 +248,9 @@ while ( $inst <= $num_instances )
    # DATM namelist
 
    set FILE1 = datm.streams.txt.CPLHISTForcing.Solar${inst_string}
-   set FILE2 = datm.streams.txt.CPLHISTForcing.nonSolarFlux${inst_string}
-   set FILE3 = datm.streams.txt.CPLHISTForcing.State1hr${inst_string}
-   set FILE4 = datm.streams.txt.CPLHISTForcing.State3hr${inst_string}
+   set FILE2 = datm.streams.txt.CPLHISTForcing.State1hr${inst_string}
+   set FILE3 = datm.streams.txt.CPLHISTForcing.State3hr${inst_string}
+   set FILE4 = datm.streams.txt.CPLHISTForcing.nonSolarFlux${inst_string}
    set DOMAINFILE = '/glade/p/cesmdata/cseg/inputdata/share/domains/domain.lnd.fv0.9x1.25_gx1v7.151020.nc'
 
    echo "domainfile = '${DOMAINFILE}'" >> ${fname}
@@ -270,16 +265,16 @@ while ( $inst <= $num_instances )
    echo "           'nomask', " >> ${fname}
    echo "           'nomask'  " >> ${fname}
    echo "tintalgo = 'coszen', " >> ${fname}
-   echo "           'nearest'," >> ${fname}
    echo "           'linear', " >> ${fname}
-   echo "           'linear'  " >> ${fname}
+   echo "           'linear', " >> ${fname}
+   echo "           'nearest' " >> ${fname}
 
    # Create stream files for each ensemble member
    set SOURCEDIR = ${dartroot}/models/clm/shell_scripts/cesm2_0
-   ${COPY} ${SOURCEDIR}/${STREAMFILE_SOLAR}        user_${FILE1} || exit 1
-   ${COPY} ${SOURCEDIR}/${STREAMFILE_NONSOLARFLUX} user_${FILE2} || exit 1
-   ${COPY} ${SOURCEDIR}/${STREAMFILE_STATE1HR}     user_${FILE3} || exit 1
-   ${COPY} ${SOURCEDIR}/${STREAMFILE_STATE3HR}     user_${FILE4} || exit 1
+   ${COPY} ${SOURCEDIR}/${STREAMFILE_SOLAR}         user_${FILE1} || exit 1
+   ${COPY} ${SOURCEDIR}/${STREAMFILE_STATE1HR}      user_${FILE2} || exit 1
+   ${COPY} ${SOURCEDIR}/${STREAMFILE_STATE3HR}      user_${FILE3} || exit 1
+   ${COPY} ${SOURCEDIR}/${STREAMFILE_NONSOLARFLUX}  user_${FILE4} || exit 1
 
    foreach FNAME ( user_datm.streams.txt*${inst_string} )
       echo "modifying $FNAME"
@@ -312,6 +307,8 @@ while ( $inst <= $num_instances )
 
    @ inst ++
 end
+
+./preview_namelists || exit 3
 
 #===============================================================================
 # This example has SourceMods that enable CLM to output solar induced fluorescence
@@ -351,8 +348,9 @@ if ( ${use_SourceMods} == TRUE ) then
          @ iarg = $iarg + 2
       end
    else
-      echo "MESSAGE - No SourceMods for this case."
-      echo "MESSAGE - No SourceMods for this case."
+      echo "ERROR - DART_params.csh use_SourceMods = ${use_SourceMods}"
+      echo "ERROR - but there are no SourceMods in ${SourceModDir}"
+      exit 3
    endif
 endif
 
