Bringing up-to-date with the trunk.
git-svn-id: https://svn-dares-dart.cgd.ucar.edu/DART/branches/wrfHydro@10756 dfa8782c-da17-4c45-ba5c-5625b50a00d6

Former-commit-id: 399826a8538571afb078a7b9d5cf3f56250d5ffc

diff --git a/models/clm/shell_scripts/CESM1_1_1_setup_hybrid b/models/clm/shell_scripts/CESM1_1_1_setup_hybrid
--- a/models/clm/shell_scripts/CESM1_1_1_setup_hybrid
+++ b/models/clm/shell_scripts/CESM1_1_1_setup_hybrid
@@ -6,7 +6,7 @@
 #
 # DART $Id$
 
-# ==============================================================================
+#*******************************************************************************
 #
 # ---------------------
 # Purpose
@@ -30,7 +30,7 @@
 # DATM: We are using an ensemble of data atmospheres. This requires modification of
 #       the stream text files (and the stream files) for each CESM instance.
 #
-# DOCN: We are using a single data ocean.
+# SOCN: We are using a stub ocean.
 #
 # Much of the complexity comes from ensuring compatibility between the namelists
 # for each instance and staging of the files. The original experiments were run
@@ -98,9 +98,7 @@
 # ./${case}.clean_build
 # ./${case}.build
 #
-# ==============================================================================
-
-
+#*******************************************************************************
 
 # ==============================================================================
 # case options:
@@ -115,7 +113,7 @@
 # num_instances The number of ensemble members.
 # ==============================================================================
 
-setenv case                 clm4_1_1_1_hybrid
+setenv case                 clm1_1_1_hybrid
 setenv compset              I_2000_CN
 setenv resolution           f09_f09
 setenv cesmtag              cesm1_1_1
@@ -182,7 +180,7 @@ setenv reftod      00000
 setenv refdate      $refyear-$refmon-$refday
 setenv reftimestamp $refyear-$refmon-$refday-$reftod
 
-setenv stagedir /glade/scratch/afox/archive/$refcase/rest/${reftimestamp}
+setenv stagedir /glade/p/image/RDA_strawman/CESM_ensembles/CLM/CLM4/I_2000_CN_f09_f09/rest/${reftimestamp}
 
 setenv bug1730_workaround  on
 setenv bug1934_workaround  on
@@ -375,6 +373,16 @@ cd ${caseroot}
 
 source ./Tools/ccsm_getenv || exit -2
 
+# Make sure the case is configured with a stub ocean and a data atmosphere.
+
+if ( (${COMP_OCN} != socn) || (${COMP_ATM} != datm) ) then
+   echo " "
+   echo "ERROR: This setup script is not appropriate for active ocean or atmospheric compsets."
+   echo "ERROR: Please use the models/CESM/shell_scripts examples for that case."
+   echo " "
+   exit -3
+endif
+
 # MAX_TASKS_PER_NODE comes from $case/Tools/mkbatch.$machine
 @ ptile = $MAX_TASKS_PER_NODE / 2
 @ nthreads = 1
@@ -528,6 +536,8 @@ endif
 # This creates the EXEROOT and RUNDIR directories.
 # ==============================================================================
 
+echo 'Setting up the case ...'
+
 ./cesm_setup
 
 if ( $status != 0 ) then
@@ -562,7 +572,6 @@ switch ( $BATCH )
    breaksw
 
    default:
-
    breaksw
 endsw
 
@@ -587,7 +596,7 @@ else
    echo "Download the appropriate files for CESM 1_1_1 from:"
    echo "http://www.image.ucar.edu/pub/DART/CESM"
    echo "untar these into your HOME directory - they will create a"
-   echo "~/cesm_1_1_1  directory with the appropriate SourceMods structure."
+   echo "~/cesm1_1_1  directory with the appropriate SourceMods structure."
    exit -4
 endif
 
@@ -655,7 +664,7 @@ while ($inst <= $num_instances)
    # ===========================================================================
    set fname = "user_nl_clm${inst_string}"
    # ===========================================================================
-   # LAND namelist
+   # LAND Namelist
    # With a RUN_TYPE=hybrid the finidat is automatically specified
    # using the REFCASE/REFDATE/REFTOD information. i.e.
    # finidat = ${stagedir}/${refcase}.clm2${inst_string}.r.${reftimestamp}.nc
@@ -721,10 +730,10 @@ while ($inst <= $num_instances)
    # For a HOP TEST ... hist_empty_htapes = .false.
    # For a HOP TEST ... use a default hist_fincl1
 
-   echo "dtime             = $clm_dtime,"             >> ${fname}
-   echo "hist_empty_htapes = .false.,"                >> ${fname}
-   echo "hist_fincl1 = 'NEP',"                        >> ${fname}
-   echo "hist_fincl2 = 'NEP','FSH','EFLX_LH_TOT_R',"  >> ${fname}
+   echo "dtime             = $clm_dtime"              >> ${fname}
+   echo "hist_empty_htapes = .false."                 >> ${fname}
+   echo "hist_fincl1 = 'NEP'"                         >> ${fname}
+   echo "hist_fincl2 = 'NEP','FSH','EFLX_LH_TOT_R'"   >> ${fname}
    echo "hist_fincl3 = 'TV','TLAI','PBOT','TBOT','TSA','RH2M_R','SNOWDP'" >> ${fname}
    echo "hist_nhtfrq = -$stop_n,1,-$stop_n"           >> ${fname}
    echo "hist_mfilt  = 1,$h1nsteps,1"                 >> ${fname}
@@ -823,7 +832,6 @@ cat << EndOfText >! stage_cesm_files
 
 set restart_time = $init_time
 
-
 # get the settings for this case from the CESM environment
 cd ${caseroot}
 source ./Tools/ccsm_getenv || exit -2
@@ -839,7 +847,6 @@ else
   echo "Date to reset files to is: ${init_time}"
 endif
 echo ''
-
 
 if ( \${CONTINUE_RUN} == TRUE ) then
 
diff --git a/models/clm/shell_scripts/CESM1_2_1_setup_pmo b/models/clm/shell_scripts/CESM1_2_1_setup_pmo
--- a/models/clm/shell_scripts/CESM1_2_1_setup_pmo
+++ b/models/clm/shell_scripts/CESM1_2_1_setup_pmo
@@ -6,7 +6,7 @@
 #
 # DART $Id$
 
-# ==============================================================================
+#*******************************************************************************
 #
 # ---------------------
 # Purpose
@@ -24,7 +24,7 @@
 # DATM: We are using an ensemble of data atmospheres. This requires modification of
 #       the stream text files (and the stream files) for each CESM instance.
 #
-# DOCN: We are using a single data ocean.
+# SOCN: We are using a stub ocean.
 #
 # This script has a counterpart that is a multi-instance setup for either a
 # free run or an assimilation experiment. To make it easy to maintain (and
@@ -92,9 +92,7 @@
 # ./${case}.clean_build
 # ./${case}.build
 #
-# ==============================================================================
-
-
+#*******************************************************************************
 
 # ==============================================================================
 # case options:
@@ -116,8 +114,9 @@
 # ==============================================================================
 # 2000_DATM%QIA_CLM40%CN_SICE_SOCN_RTM_SGLC_SWAV (I_2000_CN)       (ICN)
 # 2000_DATM%QIA_CLM45%CN_SICE_SOCN_RTM_SGLC_SWAV (I_2000_CLM45_CN) (ICLM45CN)
+# 2000_DATM%QIA_CLM45%BGC_SICE_SOCN_RTM_SGLC_SWAV (I_2000_CLM45_BGC) (ICLM45BGC)
 
-setenv case                 clm4_1_2_1_pmo
+setenv case                 clm1_2_1_pmo
 setenv compset              I_2000_CN
 setenv resolution           f09_f09
 setenv cesmtag              cesm1_2_1
@@ -178,6 +177,7 @@ setenv dartroot     /glade/u/home/${USER}/svn/DART/trunk
 #            with 80 instances, 1<= TRUTHinstance <= 80. NO LEADING ZEROS.
 #
 # stagedir   The directory location of the reference case files.
+#            This will surely change based on the compset and machine.
 #
 # bug1730_workaround   If ANY history file will be created in the 'vector' format,
 #                      this should be set to 'on'.
@@ -200,7 +200,7 @@ setenv TRUTHinstance 23
 setenv refdate      $refyear-$refmon-$refday
 setenv reftimestamp $refyear-$refmon-$refday-$reftod
 
-setenv stagedir /glade/scratch/afox/archive/$refcase/rest/${reftimestamp}
+setenv stagedir /glade/p/image/RDA_strawman/CESM_ensembles/CLM/CLM4/I_2000_CN_f09_f09/rest/${reftimestamp}
 
 setenv bug1730_workaround  on
 setenv bug1934_workaround  on
@@ -392,6 +392,16 @@ endif
 cd ${caseroot}
 
 source ./Tools/ccsm_getenv || exit -2
+
+# Make sure the case is configured with a stub ocean and a data atmosphere.
+
+if ( (${COMP_OCN} != socn) || (${COMP_ATM} != datm) ) then
+   echo " "
+   echo "ERROR: This setup script is not appropriate for active ocean or atmospheric compsets."
+   echo "ERROR: Please use the models/CESM/shell_scripts examples for that case."
+   echo " "
+   exit -3
+endif
 
 # MAX_TASKS_PER_NODE comes from $case/Tools/mkbatch.$machine
 @ ptile = $MAX_TASKS_PER_NODE / 2
@@ -603,7 +613,7 @@ else
    echo "Download the appropriate files for CESM 1_2_1 from:"
    echo "http://www.image.ucar.edu/pub/DART/CESM"
    echo "untar these into your HOME directory - they will create a"
-   echo "~/cesm_1_2_1  directory with the appropriate SourceMods structure."
+   echo "~/cesm1_2_1  directory with the appropriate SourceMods structure."
    exit -4
 endif
 
@@ -674,7 +684,6 @@ switch ( $BATCH )
    breaksw
 
    default:
-
    breaksw
 endsw
 
@@ -717,7 +726,7 @@ while ($inst <= 1)
    # ===========================================================================
    set fname = "user_nl_clm${inst_string}"
    # ===========================================================================
-   # LAND namelist
+   # LAND Namelist
    # With a RUN_TYPE=hybrid the finidat is automatically specified
    # using the REFCASE/REFDATE/REFTOD information. i.e.
    # finidat = ${stagedir}/${refcase}.clm2${inst_string}.r.${reftimestamp}.nc
@@ -783,10 +792,10 @@ while ($inst <= 1)
    # For a HOP TEST ... hist_empty_htapes = .false.
    # For a HOP TEST ... use a default hist_fincl1
 
-   echo "dtime             = $clm_dtime,"             >> ${fname}
-   echo "hist_empty_htapes = .false.,"                >> ${fname}
-   echo "hist_fincl1 = 'NEP',"                        >> ${fname}
-   echo "hist_fincl2 = 'NEP','FSH','EFLX_LH_TOT_R',"  >> ${fname}
+   echo "dtime             = $clm_dtime"              >> ${fname}
+   echo "hist_empty_htapes = .false."                 >> ${fname}
+   echo "hist_fincl1 = 'NEP'"                         >> ${fname}
+   echo "hist_fincl2 = 'NEP','FSH','EFLX_LH_TOT_R'"   >> ${fname}
    echo "hist_fincl3 = 'TV','TLAI','PBOT','TBOT','TSA','RH2M_R','SNOWDP'" >> ${fname}
    echo "hist_nhtfrq = -$stop_n,1,-$stop_n"           >> ${fname}
    echo "hist_mfilt  = 1,$h1nsteps,1"                 >> ${fname}
@@ -889,7 +898,6 @@ cat << EndOfText >! stage_cesm_files
 
 set restart_time = $init_time
 
-
 # get the settings for this case from the CESM environment
 cd ${caseroot}
 source ./Tools/ccsm_getenv || exit -2
@@ -905,7 +913,6 @@ else
   echo "Date to reset files to is: ${init_time}"
 endif
 echo ''
-
 
 if ( \${CONTINUE_RUN} == TRUE ) then
 
